### ISSUE TITLE
Bluetooth random disconnects intel(R) AX200

### ISSUE THREAD

**Issue by spbisc97** [pop-os/linux-firmware#13]
Hi, I have an intel AX200, and while the wifi works perfectly, the Bluetooth randomly disconnects from devices. 
This seems to be a common error that intel has fixed a few days ago: [Reddit Broken ax200](https://www.reddit.com/r/linuxhardware/comments/m21yhj/fyi_bluetooth_on_intel_ax200_currently_broken/)

It is possible to add those fixes in the package?

Thanks!

**Comment by spbisc97** [comment]
I have fixed this issue using the original[ Linux Firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/)
Just 3 commands 
```Bash 
git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
cd linux-firmware 
sudo make install 
systemctl reboot 
```
this updates the files relative to mainline


I think this could be solved also by merging the updates of original [Linux-Firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/) into this .

PS. I think the problem are the iwlwifi-*-62.ucode microcode files

**Comment by yektaparlak** [comment]
> I have fixed this issue using the original[ Linux Firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/) Just 3 commands
> 
> ```shell
> git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
> cd linux-firmware 
> sudo make install 
> systemctl reboot 
> ```
> 
> this updates the files relative to mainline
> 
> I think this could be solved also by merging the updates of the original [Linux-Firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/) into this.
> 
> PS. I think the problem is the iwlwifi-*-62.ucode microcode files. Going back to 59 fixes this problem and doesn't add any. I have been using this for 3 days, I'll post if I see any.
> 
> The specific file for AX200 is iwlwifi-cc-a0-62.ucode -> iwlwifi-cc-a0-59.ucode

That implementation successfully fixed my issue. Thank you

**Comment by gabriele2000** [comment]
I have the same problem, I just migrated from the Realtek 3168 or something, to the Intel Killer 1675 (Intel AX210).

I had this random bluetooth disconnection with the other one, but I have this issue with the AX210 too...
Digging out of desperation everything points to "linux-firmware".

Also, the issue becomes even more severe if I try to connect the Dualsense controller after connecting my SONY-WH1000XM5.
