### ISSUE TITLE
No obvious way to downgrade to previous version

### ISSUE THREAD

**Issue by mpartel** [pop-os/linux-firmware#31]
Due to #30, I tried to find a way to install the previous version, but https://apt-origin.pop-os.org/release/pool/jammy/linux-firmware/ only has the very latest version.

**Comment by mmstick** [comment]
It'd be better to fix the issue so downgrading isn't necessary

**Comment by mpartel** [comment]
:disappointed: 
I'm willing to spend time debugging things, but in the meantime I also kinda need my computer to work. Rollbackability is IMO a pretty standard best practice in software deployment.

**Comment by mmstick** [comment]
This is why we would like to have an immutable core with A/B roots and snapshots in the next iteration of Pop!_OS.
