### ISSUE TITLE
Rebase onto 20230629

### ISSUE THREAD

**Issue by 0dinD** [pop-os/linux-firmware#34]
I see that Ubuntu has recently released https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-firmware/tag/?h=Ubuntu-20230629.gitee91452d-0ubuntu1

I think this release contains some patches for MediaTek MT7921 and MT7922 (for example: https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-firmware/commit/?h=Ubuntu-20230629.gitee91452d-0ubuntu1&id=5ce06b9e07a748b66d0a7d8329563b13f425a6f1), so it would be interesting to see if it has any effect on pop-os/pop#530. See also:

- https://github.com/pop-os/pop/issues/530#issuecomment-1613617658
- https://github.com/pop-os/pop/issues/530#issuecomment-1614732241
- https://github.com/pop-os/pop/issues/530#issuecomment-1614776565
- https://github.com/pop-os/pop/issues/530#issuecomment-1617996716

**Comment by pktiuk** [comment]
There is a related PR: https://github.com/pop-os/linux-firmware/pull/35

**Comment by 0dinD** [comment]
#35 has now been merged, so I'll close this issue now. The `20230629` version of `linux-firmware` does not seem to be available from the APT repository yet though, probably because it hasn't been released here: https://github.com/pop-os/repo-release

**Comment by pktiuk** [comment]
I hope this will be released soon

**Comment by leviport** [comment]
I've released it. It should be available shortly.
