### ISSUE TITLE
linux-firmware-2024091 broke Wi-Fi

### ISSUE THREAD

**Issue by Psyhackological** [pop-os/linux-firmware#49]
## Issue
Infinite connection loop, cannot connect to anything Wi-Fi related. The package `linux-firmware`
bad version `20240913.gita34e7a5f-0ubuntu2+system76~1729519989~24.04~2225517`
good version: `20240318.git3b128b60-0ubuntu2.5`

## Logs
I attach my `sudo journalctl -f` in [wifi_dump.log](https://github.com/user-attachments/files/17846095/wifi_dump.log).

## Solution
I just came back from `chroot`-ed environment. I downgraded to the previous version `linux-firmware=20240318.git3b128b60-0ubuntu2.5`.

## Fasfetch
```bash
konradkon@pop-os
----------------
OS: Pop!_OS noble 24.04 x86_64
Host: Serval WS (serw13)
Kernel: Linux 6.9.3-76060903-generic
Uptime: 12 mins
Packages: 3316 (dpkg), 35 (flatpak-user), 1 (pacstall)
Shell: fish 3.7.0
Display (DELL G2722HS): 1920x1080 @ 165 Hz in 27" [External]
Display (BOE0BB7): 3840x2160 @ 144 Hz (as 1920x1080) in 17" [Built-in]
DE: COSMIC
WM: cosmic-comp (Wayland)
Theme: Yaru [GTK3]
Icons: Yaru [GTK3]
Cursor: Cosmic
Terminal: cosmic-term
CPU: 13th Gen Intel(R) Core(TM) i9-13900HX (32) @ 5.40 GHz
GPU 1: NVIDIA GeForce RTX 4060 Max-Q / Mobile
GPU 2: Intel Raptor Lake-S UHD Graphics @ 1.65 GHz [Integrated]
Memory: 8.36 GiB / 31.18 GiB (27%)
Swap: 0 B / 16.00 GiB (0%)
Disk (/): 39.63 GiB / 200.00 GiB (20%) - btrfs
Disk (/home): 342.33 GiB / 730.51 GiB (47%) - btrfs
Local IP (wlp0s20f3): 192.168.0.103/24
Battery (BAT): 100% [AC Connected]
Locale: en_GB.UTF-8
```

**Comment by Cyberschorsch** [comment]
Also see https://github.com/pop-os/pop/issues/3409

**Comment by Psyhackological** [comment]
Oh, I have expected the issue here, thanks for mentioning it @Cyberschorsch

**Comment by leviport** [comment]
This is the correct repo, but since there's already more people in https://github.com/pop-os/pop/issues/3409, so I'll close this in favor of that report.

For now, downgrading linux-firmware is a workaround: 
```
sudo apt install linux-firmware=20240318.git3b128b60-0ubuntu2.5
```
